CREATE TABLE IF NOT EXISTS DF_PLAN
(
    ID                INT NOT NULL AUTO_INCREMENT,
    PLAN_ID           VARCHAR(64) NOT NULL,
    PLAN_TYPE         VARCHAR(128) NOT NULL,
    SPECIFICATION1    VARCHAR(128) NOT NULL,
    SPECIFICATION2    VARCHAR(128) NOT NULL,
    PRICE             DOUBLE(10,2)  NOT NULL,
    CYCLE             VARCHAR(2) NOT NULL,
    REGION            VARCHAR(30) NOT NULL,
    CREATE_TIME       DATETIME,
    STATUS            VARCHAR(2) NOT NULL,
    PRIMARY KEY (ID)
)  DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_ITEM_STAT
(
   STAT_KEY     VARCHAR(255) NOT NULL COMMENT '3*255 = 765 < 767',
   STAT_VALUE   INT NOT NULL,
   PRIMARY KEY (STAT_KEY)
)  DEFAULT CHARSET=UTF8;
