CREATE TABLE IF NOT EXISTS DF_PLAN_REGION
(
    ID                TINYINT NOT NULL AUTO_INCREMENT,
    REGION            VARCHAR(30) NOT NULL,
    REGION_DESCRIBE   VARCHAR(128) NOT NULL,
    IDENTIFICATION    VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
) DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_PLAN
(
    ID                INT NOT NULL AUTO_INCREMENT,
    PLAN_ID           VARCHAR(64) NOT NULL,
    PLAN_NAME         VARCHAR(128) NOT NULL,
    PLAN_TYPE         VARCHAR(128) NOT NULL,
    BELONG            VARCHAR(128) NOT NULL,
    PLAN_LEVEL        TINYINT NOT NULL,
    SPECIFICATION1    VARCHAR(128) NOT NULL,
    SPECIFICATION2    VARCHAR(128) NOT NULL,
    PRICE             DOUBLE(10,2)  NOT NULL,
    CYCLE             VARCHAR(2) NOT NULL,
    CREATE_TIME       DATETIME,
    REGION_ID         TINYINT NOT NULL,
    STATUS            VARCHAR(2) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ID FOREIGN KEY (REGION_ID) REFERENCES DF_PLAN_REGION (ID)
) DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_ITEM_STAT
(
   STAT_KEY     VARCHAR(255) NOT NULL COMMENT '3*255 = 765 < 767',
   STAT_VALUE   INT NOT NULL,
   PRIMARY KEY (STAT_KEY)
) DEFAULT CHARSET=UTF8;
